### ISSUE TITLE
TypeError: url.indexOf is not a function on line

### ISSUE THREAD

**Issue by jasperf** [soflyy/oxygen-bugs-and-features#1962]
Working with basic main 2.0 template in Firefox Developer 87.0b5 (64-bit) and some CSS to create an accordion effect

```
.page-template-default div.panel {
    max-height: 0;
    overflow: hidden;
    opacity: 0;
}

.page-template-default div.panel.show {
    opacity: 1;
  	min-height: 150px;
    max-height: 100%;
}

.parent-pageid-4698 .oxy-dynamic-list span p {
    padding-left: 10px;
}

.parent-pageid-4698 .ct-div-block panel show {
  box-shadow:none !important;
}
```

I am getting this error

```
TypeError: url.indexOf is not a function on line #10353 in https://workcycles.com/f-a-q/workcycles-fr8-faq/?ct_builder=true&ct_inner=true&oxygen_iframe=true line 129 > injectedScript
```
while working on the page / template CSS.

In the console log I see jQuery recording migration warnings and I also see this webfont error

```
Error: WebFont is not defined
s.loadWebFont@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:12:3579
$e.getSelectorStyles@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:14:107309
$e.getSingleClassCSS@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:14:86943
i/<@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:14:17168
$e.generateDynamicBackgrounds@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:14:14894
i@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:14:17091
$e.outputCSSOptions@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:14:17222
v.pageSettingsUpdate@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:9:30549
@https://workcycles.com/wp-content/plugins/oxygen/component-framework/angular/controllers/iframe.min.js?ver=3.6.1:14:116769
$digest@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:14133:29
$apply@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:14395:24
bootstrapApply@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:1437:15
invoke@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:4138:17
doBootstrap@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:1435:14
bootstrap@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:1455:12
angularInit@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:1349:14
@https://workcycles.com/wp-content/plugins/load-oxygen-locally/assets/js/angular.js?ver=1.4.2:25912:16
mightThrow@https://workcycles.com/wp-includes/js/jquery/jquery.js?ver=3.5.1:3762:29
resolve/</process<@https://workcycles.com/wp-includes/js/jquery/jquery.js?ver=3.5.1:3830:12
```

I am using Oxygen Builder 3.6 and latest Wordpress version 5.6.2

**Comment by jasperf** [comment]
Hmm, may be related to

```
Uncaught TypeError: url.indexOf is not a function
    load jQuery
    init https://workcycles.com/wp-content/plugins/gdpr-cookie-compliance/dist/scripts/main.js?ver=4.4.6:2
    fire https://workcycles.com/wp-content/plugins/gdpr-cookie-compliance/dist/scripts/main.js?ver=4.4.6:2
    loadEvents https://workcycles.com/wp-content/plugins/gdpr-cookie-compliance/dist/scripts/main.js?ver=4.4.6:2
    jQuery 13

```

Need to see why that happens here using the GDPR Cookie Compliance Plugin.

**Comment by KittenCodes** [comment]
@jasperf It sounds like this is caused by a plugin conflict. Please run a plugin conflict test: https://pluginconflict.com/?plugin=Oxygen.

If the error persists when Oxygen is the only active plugin on your site, please open a support ticket: https://oxygenbuilder.com/support.
