### ISSUE TITLE
Essential Grid doesn't load on 2.2 RC1

### ISSUE THREAD

**Issue by sunnyt7** [soflyy/oxygen-bugs-and-features#78]
When using Oxygen 2.2 RC1 with Essential Grid (doesn't matter what version), you get this error in the browser console:

TypeError: jQuery(...).tpessential is not a function

I know there was a fix before about setting the parent to display: block, but I have done that and this looks to be a different issue.

I tried loading Essential Grid in the Try Oxygen sandbox, and version 2.1 there displayed the grid perfectly. When I uninstalled 2.1 and installed 2.2 RC1, and I got the error.

Here are the links:

Site: http://impossible-tapir.w6.wpsandbox.pro/

Login: http://impossible-tapir.w6.wpsandbox.pro?upass=i332rOs0KFWa

**Comment by mikeingz** [comment]
I can confirm because I tried it too.
The problem comes from the JS files from Essential Grid. They are simply missing (not imported in the page) when we add the shortcode in Oxygen 2.2 RC1.
Hence the jquery error.

**Comment by louisreingold** [comment]
We'll release an RC2 that addresses this and can be tested further before releasing the final 2.2.

**Comment by louisreingold** [comment]
After further testing, it appears this also happens in Oxygen 2.1.2, and therefore won't be fixed in 2.2 RC2, as this is not a new bug.

I've installed 2.1.2 at http://impossible-tapir.w6.wpsandbox.pro/ and the same thing happens.

Can you provide exact steps to follow to make it work with 2.1 but demonstrate it is broken in 2.2?

**Comment by louisreingold** [comment]
This is not the same as #1608.

**Comment by sunnyt7** [comment]
My exact steps were:

- launch new example site on https://oxygenbuilder.com/try/
- upload Essential Grid (latest version)
- make a test grid
- create new page, create section with parent element set to block, insert Shortcode element with the shortcode given by Essential Grid
- save page... everything worked

I just tried it on RC2 now though and it looks like everything works again.

**Comment by louisreingold** [comment]
You're saying the grid didn't display on the frontend with RC1 but now it does in RC2?

Or you're saying the grid didn't display on the backend in RC1 but it does in RC2?

I was not able to get the grid to display on the backend in 2.1.2, RC1, or RC2.

**Comment by mikeingz** [comment]
I tested it again and here is a summary :

Oxygen 2.1.2
Backend : no (doesn't show up because 'TypeError: jQuery(...).tpessential is not a function')
Frontend : yes

Oxygen 2.2 RC1
Backend : no
Frontend : no

Oxygen 2.2 RC2
Backend : no
Frontend : yes

**Comment by sunnyt7** [comment]
Yeah, that's what I was seeing as well.

**Comment by sbwp** [comment]
Same problem in final 2.2

**Comment by sbwp** [comment]
After a little bit of digging it seems that the js assets form themepunch are not loaded in Oxygen 
jquery.themepunch.tools.min.js and jquery.themepunch.essential.min.js

I fixed it by manually loading the scripts like this:

`wp_enqueue_script( 'oxygenessgridfix-js', plugins_url() . '/essential-grid/public/assets/js/jquery.themepunch.tools.min.js', '', '', true );
wp_enqueue_script( 'oxygenessgridfix2-js', plugins_url() . '/essential-grid/public/assets/js/jquery.themepunch.essential.min.js', '', '', true );
`

**Comment by KittenCodes** [comment]
@sunnyt7 I don't have a copy of Essential Grid to be able to test this in the latest version of Oxygen. Unfortunately, the Sandbox you set up has expired. If you're still having problems, please install Essential Grid on a new Sandbox and send us the login.

You can create a Sandbox site here: https://oxygenbuilder.com/try/.
